### ISSUE TITLE
Arrow Function this

### ISSUE THREAD

**Issue by kobezzza** [termi/es6-transpiler#1]
Сейчас, как я понял для прокидывания this используется bind - это не очень хорошо, т.к. bind функции реально работают гораздо медленней простых (это заметно в коде, где много итераторов, падение скорости во всех современных браузерах, http://jsperf.com/bind/3).

Лучше прокидывать this через замыкание, как это делается в TypeScript или в моём NeJS.

**Comment by termi** [comment]
Да, ты прав. Переделаю. Я просто смотрел, как это сделано в traceur compiler

**Comment by termi** [comment]
@kobezzza Зацени [es6-arrowFunctions-out.js#L24-L25](https://github.com/termi/es6-transpiler/blob/e1f984f1b964c599d18c4f0e26cd6ed52655151e/tests/es6-arrowFunctions-out.js#L24-L25) : тут `this$1` - это моя переменная, а `this$0` была изначально в коде. Т.е. я проверяю на то, чтобы не создать переменную с уже существующим именем. Ну и из этого примера видно, что я не стал заморачиваться с анализом, если ли уже переменная, которая хранит в себе `this`, или нету - слишком сложно.

**Comment by kobezzza** [comment]
Отличная новость! Теперь могу заменить свой костыльный транслятор целиком :)

**Comment by termi** [comment]
я ещё в npm не выкладывал. сегодня ещё раз всё проверю и выложу
