### ISSUE TITLE
run throws exception for empty strings

### ISSUE THREAD

**Issue by davewasmer** [termi/es6-transpiler#27]
Calling `run()` with an empty string for the `src` option throws an exception. I would expect it to return an empty string for `src`:

``` javascript
> var es6 = require("es6-transpiler");
> es6.run({src: ""});
// Error: Input not found undefined
//  at Object.run (/Users/daw/scratch/node_modules/es6-transpiler/build/es5/es6-transpiler.js ...
```

Seems to be coming from the `if` check on [line 146](https://github.com/termi/es6-transpiler/blob/master/es6-transpiler.js#L146) in `es6-transpiler.js`:

``` javascript
if( !this.ast && this.src ) {
  // ...
else {
  throw new Error("Input not found " + config.filename);
}
```

I assume the purpose is to check for the existence of `options.src`, but JavaScript will coerce the empty string to boolean false.

Happy to submit PR if you'd like, figured I double check this was actually unintended behavior first.

**Comment by termi** [comment]
@davewasmer I will glad to see your PR.
