### ISSUE TITLE
Class member modifiers support

### ISSUE THREAD

**Issue by dy** [termi/es6-transpiler#28]
None of ES6 compilers now support a quite useful [standard proposal](http://wiki.ecmascript.org/doku.php?id=harmony:classes#member_modifiers) — `public` member modifier, which’d allow to declare prototype variable. For example:

``` js
class N{
    public defaults = {
        max: 12,
        min: 1
    }
}
```

Supposedly should compile to 

``` js
N.prototype.defaults = { min:1, max: 12}
```

**Comment by termi** [comment]
**public** word doesn't supported by [esprima](https://github.com/ariya/esprima) and it's not a part of es6 specification draft  yet as I can see.

**Comment by yuri-karadzhov** [comment]
Can you add `public` and `static` features to experimental part of compiller cause they are really useful to define class properties.

**Comment by termi** [comment]
I added support for such features:

``` javascript
class TEST {
    static c = 1;
    static A;

    public f = 123;
    public G;
}

```

you must pass the option `classesExtras = {staticProperty: true, publicProperty: true}` to the config.
