### ISSUE TITLE
Don’t work at all

### ISSUE THREAD

**Issue by sapegin** [termi/es6-transpiler#3]
It tries to import [file](https://github.com/termi/es6-transpiler/blob/master/es6-transpiler.js#L20) that’s [listed](https://github.com/termi/es6-transpiler/blob/master/.gitignore#L17) in gitignore.

**Comment by termi** [comment]
Fixed this in 44883f96da66b15144bdd5d3ab8b62ed70eae2d7
moreover, I added an array comprehensions support in dde7364923da515a1b77bd8a4f17ea93c396daaf

Update npm version now to 0.7.0

**Comment by termi** [comment]
I am glad to say that I am created a [grunt task](https://github.com/termi/grunt-es6-transpiler/) for ease using
