### ISSUE TITLE
Semicolon insertion for generated lines with leading [ ( characters

### ISSUE THREAD

**Issue by timoxley** [termi/es6-transpiler#34]
The transpiler should probably insert semicolons wherever they would be inserted automatically in the source code, otherwise it can generate invalid JS when semicolons are omitted. See example below.

Maybe it'd be possible to only auto-insert them whenever a _generated_ line will be broken by their omission e.g. any generated line starting with ( or [.

edit: found more minimal test case.

ES6 input:

``` js
let a = {
  b: {
    c: () => 0
  }
}

let exec = () => {
  let args = []
  a.b.c(...args)
}

exec()
```

Generated output:

``` js
var a = {
  b: {
    c: function()  {return 0}
  }
}

var exec = function()  {var $D$0;function ITER$0(v,f){var $Symbol_iterator=typeof Symbol!=='undefined'&&Symbol.iterator||'@@iterator';if(v){if(Array.isArray(v))return f?v.slice():v;var i,r;if(typeof v==='object'&&typeof (f=v[$Symbol_iterator])==='function'){i=f.call(v);r=[];while((f=i['next']()),f['done']!==true)r.push(f['value']);return r;}}throw new Error(v+' is not iterable')};
  var args = []
  ($D$0 = a.b).c.apply($D$0, ITER$0(args))
;$D$0 = void 0}

exec()
```

Error: 

``` js
  ($D$0 = a.b).c.apply($D$0, ITER$0(args))
  ^
TypeError: object is not a function
```

Problem is there's no semi between these two lines, so it's interpreted as `var args = []($D$0 = a.b)`, but would be valid es6 without the transpiler.

``` js
...
 var args = []
  ($D$0 = a.b).c.apply($D$0, ITER$0(args))
...
```

Perhaps the most minimal fix would be to just add a semi for the specific case of accessing arrow functions nested in other objects.

**Comment by timoxley** [comment]
Dug into this a bit, it's [this spread handling code](https://github.com/termi/es6-transpiler/blob/ce76ed49bb4fffe6866d3f5d8ca6ffb96c0c7fed/transpiler/spread.js#L90-L94) causing the problem: 

``` js
                let tempVar = core.getScopeTempVar(node.callee.object, node.$scope);

                this.alter.wrap(
                    node.callee.object.range[0]
                    , node.callee.object.range[1]
                    , "(" + tempVar + " = "
                    , ")"
                );

                expressionAfter =
                    ".apply(" + tempVar
                    + ", "
                ;

                core.setScopeTempVar(tempVar, node, node.$scope, true);
```

[Source](https://github.com/termi/es6-transpiler/blob/ce76ed49bb4fffe6866d3f5d8ca6ffb96c0c7fed/transpiler/spread.js#L90-L94)

One can fix this specific issue with:

``` js
                this.alter.wrap(
                    node.callee.object.range[0]
                    , node.callee.object.range[1]
                    , ";(" + tempVar + " = " // added leading semi
                    , ")"
                );
```

But this causes a bunch of other issues if the statement isn't at the start of the line, e.g:

``` js
console.log( ;($D$0 = obj$0.obj).test.apply($D$0, [28].concat(ITER$0(arr))) === "THIS|28|6|3" )
```

``` js
 var T$3 = ;($D$0 = obj$0.obj).test.apply($D$0, [27].concat(ITER$0(arr)));
```

so looks like it requires some probing around the context to detect if there's any leading code… or perhaps some other type of handling, going to have to leave this to you though, sorry!

**Comment by termi** [comment]
I will fix it soon
